### ISSUE TITLE
fullscreen leading to childNodes crash

### ISSUE THREAD

**Issue by emtenet** [elm/virtual-dom#128]
I have encountered the following exception `TypeError: Cannot read property 'childNodes' of undefined at _VirtualDom_addDomNodesHelp` whilst migrating a project to elm 0.19.

Whilst preparing a SSCCE encountered a related exception `TypeError: Cannot set property 'disabled' of undefined at _VirtualDom_applyFacts`.

So I have two SSCCEs:
* https://gist.github.com/emtenet/7f348403295759b7a25d573063aefca0
* https://gist.github.com/emtenet/bfc99a0d954fd3c2b2f8e185278523e4

With both examples, click the "Click" button twice. The second click causes the exception.

**Comment by emtenet** [comment]
The SSCCE where prepared with elm 0.19 compiled on NetBSD from sources on the 17th of May.
The SSCCE where tested in Chrome 66 on Windows 10

**Comment by evancz** [comment]
The issue is very surprising! Here is some HTML that will log `0` on the console:

```html
<!DOCTYPE HTML>
<head>
<script>
  window.addEventListener("load", function() {
    console.log(document.body.childNodes.length);
  });
</script>
</head><body></body></html>
```

And here is some HTML that will log `1` on the console:

```html
<!DOCTYPE HTML>
<head>
<script>
  window.addEventListener("load", function() {
    console.log(document.body.childNodes.length);
  });
</script>
</head><body></body>
</html>
```

It seems that everything after the `</body>` and before `</html>` is added to the body after your code runs, but before onload.

I have some ideas of how to detect this, but it is pretty tricky!
